apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: demo
data:
  APP_GREETING: "Hello from Nifty's kubeadm cluster"
  APP_ENV: "lab"
---
apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: demo
type: Opaque
stringData:                       # stringData = plain text; k8s base64-encodes it for you
  API_TOKEN: "super-secret-token-change-me"
